apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: prometheus.demo.local
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090